### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by chzyer** [smirn0v/imux#1]
When I execute ./imux, it outputs `[xxxxxx] connected`
and then I try telnet localhost 31337, it reports `[-] failed to perform mux connect on device`
what else can I do?

It seems crash by `USBMuxConnectByPort`, the ret code is 61.
My OSX version is 10.10, and iOS version is 8.1.

Is needs make sure that OpenSSH installed on iphone?

**Comment by smirn0v** [comment]
Hi!
Current version have hardcoded ports and expects iOS Device to have 22 port (SSH) opened.
You have to install SSH server on your iPhone and make sure it is running.

**Comment by chzyer** [comment]
Thanks to reply!
I found the reason is that it missing the running SSH server on my iPhone.
Thanks again.
